# Secret file that store configuration data that are SECRET like credentials as keys-value pairs
apiVersion: v1
kind: Secret
metadata:
        name: mongo-secret
type: Opaque

data:
        mongo-user: c3lzYWRtaW4K
        mongo-password: cGFzc3dvcmQK
